### ISSUE TITLE
Quiz question does not show options at the end of two science games

### ISSUE THREAD

**Issue by vs-ranjani** [pila-project/pila-platform#127] opened 2024-05-06 09:24 UTC
This happens in both the mushroom game and the paper planes game:

![image](https://github.com/pila-project/pila-platform/assets/168413098/ae8ab85b-d6b7-40c0-a01a-2089e0bd47fa)

**Comment by jasonford** [comment] 2024-05-06 18:35
@stephanemagnenat I think this is probably on the candli side, but happy to jump in if there is an issue on our end. @vs-ranjani is this repeatable/ it might be useful to include the console if there are errors or warnings here

**Comment by stephanemagnenat** [comment] 2024-05-06 19:49
Yes we discussed this during our discussion with OECD this afternoon. It is not a bug, just a behavior that is a bit strange UI-wise. We agreed to hide the option completely once it is selected, and only leave "Submit my result" which will close the game. It might also make sense to remove the  "Back to the experiment button" as the quiz is completed, but I guess we can keep it if people want to have a bit more fun before "finishing" the experience.

**Comment by jasonford** [comment] 2024-05-07 03:38
@stephanemagnenat sounds good. Thanks for the update. I'll close it here since the concerned code is out of this repo, but if keeping such issues open here helps you manage them in any way, happy to do so.

**Closed as completed by jasonford** 2024-05-07 03:38 UTC
Labels: Pending OECD Input

**Comment by OECDPILA** [comment] 2024-05-07 07:54
thanks both @stephanemagnenat @jasonford
