### ISSUE TITLE
Even when I delete default content on PILA Create, some of it still shows up (this also means I am unable to create new content)

### ISSUE THREAD

**Issue by vs-ranjani** [pila-project/pila-platform#86] opened 2024-04-30 13:26 UTC
![image](https://github.com/pila-project/pila-platform/assets/168413098/20aa8d5c-6024-47d6-9b28-7790728f09e8)

I was trying to delete all default content on PILA Create and start from a blank slate but the default matching question on basketball remains (although it disappeared on the sidebar).

**Comment by mthomasmcclain** [comment] 2024-04-30 23:42
I can't reproduce this, so I am closing.  If you see it again, please reopen.

**Comment by jasonford** [comment] 2024-04-30 23:43
@vs-ranjani thanks for the report! If you do see it again, could you please right click the page and click "inspect" to see if there is an error logged to the console?

**Comment by vs-ranjani** [comment] 2024-05-02 08:38
Sure! So, I tried to do the same today and here's what I see:

![image](https://github.com/pila-project/pila-platform/assets/168413098/1420b8b0-b11b-4229-a6d1-207331bdd744)
![image](https://github.com/pila-project/pila-platform/assets/168413098/1dada55f-ac51-4b53-96bc-9c9625224cd1)


Basically, when I delete all default content and click on 'Create New' for a matching type question on the home page, this shows up.

**Comment by vs-ranjani** [comment] 2024-05-10 12:28
Sorry to bring this up again! But I noticed this with the sequence wrapper again - when I delete all default content and try to create a new sequence it directs me to a task preview (of a default task that I'd deleted) and doesn't allow me to go back/create a new task. I've flagged it to Eren too!

![image](https://github.com/pila-project/pila-platform/assets/168413098/c7657c9d-2497-40b7-9438-1ce6ad0d2669)

**Comment by erenkahraman** [comment] 2024-05-10 13:04
I've checked other items, and they have the same issue. If there is no item, and if it's going to be the first one, the problem is that the item shows us the default "preview" rather than the customizer. The way we create a new sequence builder is by dragging any type of item into the sequence builder. So basically, we have to be able to see the customizer first. I'm working on it.

**Comment by mthomasmcclain** [comment] 2024-05-10 17:41
Okay, Eren and I cornered this. I pushed a fix that I'm 90% sure will work.  And I added some warnings for the likely error condition so if it recurrs the console will give us hints.

**If you see it again, please repopen and take a screenshot of the page and console**.  Hopefully it'll be gone forever, and if it recurs hopefully those console logs will help squash for good.

**Closed as completed by mthomasmcclain** 2024-05-10 17:41 UTC
Labels: Priority - Low
