### ISSUE TITLE
Bug - One student could not re-enter a task in their assignments page of their student account after exiting. 

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#132] opened 2024-05-06 09:51 UTC
(Medium priority)

They kept clicking on the 'play' button and it wouldn't reload.

**Comment by jasonford** [comment] 2024-05-06 18:41
@OECDPILA any chance this is repeatable/ we could get a console error image? It sounds like this was on the candli 'play' button? If so I'll add the new Candli tag and ping Stéphane

**Comment by OECDPILA** [comment] 2024-05-07 08:04
This was on the assignment card in the student account. "I was pressing on 'Play' but it did nothing, and same thing if I tried to click on the icon of the task. The bug solved itself not too long after though" Please see screenshot.
![image](https://github.com/pila-project/pila-platform/assets/145113767/2bf31024-5d91-4ac9-898e-0be0c1d4220f)

**Comment by jasonford** [comment] 2024-05-09 17:19
@OECDPILA Closing this because it is hard to reproduce. Might have been a browser bug/performance issue because of a teams meeting being open or something like that. If pops up again, please reopen/create new issue!

**Closed as completed by jasonford** 2024-05-09 17:19 UTC
Labels: Priority - Medium
